#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e

cd "$(dirname $0)"/..

# find the installers and run them iteratively
find . -name install.sh | while read installer ; do sh -c "${installer}" ; done

echo "› run brewfile"
brew bundle

echo "› Setting defaults"
# Set defaults
find . -name set-defaults.sh | while read installer ; do echo "> Setting defaults for ${installer}"; sh -c "${installer}" ; done

